#!/bin/sh

### BEGIN INIT INFO
# Provides:          squeezelite
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      autofs $network $named alsa-utils pulseaudio
# Should-Stop:       autofs $network $named alsa-utils pulseaudio
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SqueezeBox Lite
# Description:       Start the SqueezeBox Lite service
#                    for network access to the local audio queue.
### END INIT INFO

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=squeezelite
DESC="SqueezeBox Lite"
DAEMON=/opt/squeezelite/squeezelite-static
START_SL=true
SL_OPTS="-n raspberrypi -P /var/run/$NAME.pid -z"

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

PIDFILE=/var/run/$NAME.pid

sl_start () {
    if [ "$START_SL" != "true" ]; then
        log_action_msg "Not starting $DESC: disabled by /etc/default/$NAME".
        exit 0
    fi

    log_daemon_msg "Starting $DESC" "$NAME"

    start-stop-daemon --start --quiet --oknodo --pidfile "$PIDFILE" \
        --exec $DAEMON -- $SL_OPTS

    log_end_msg $?
}

sl_stop () {
    if [ "$START_SL" != "true" ]; then
        log_failure_msg "Not stopping $DESC: disabled by /etc/default/$NAME".
        exit 0
    fi

    log_daemon_msg "Stopping $DESC" "$NAME"

    start-stop-daemon --stop --quiet --oknodo --retry 5 --pidfile "$PIDFILE" \
        --exec $DAEMON

    log_end_msg $?
}

case "$1" in
    start)
        sl_start
        ;;
    stop)
        sl_stop
        ;;
    status)
    	status_of_proc -p $PIDFILE $DAEMON $NAME
	;;
    restart|force-reload)
        sl_stop
        sl_start
        ;;
    force-start)
        sl_start
        ;;
    force-restart)
        sl_stop
        sl_start
        ;;
    force-reload)
	sl_stop
	sl_start
	;;
    *)
        echo "Usage: $0 {start|start-create-db|stop|restart|force-reload}"
        exit 2
        ;;
esac
